title: "Vex Whitepaper"
description: "A Vex platform whitepaper on bringing public market mechanics to private equity and debt"
baseurl: "/vex-whitepaper"
url: "https://vex-holdings.github.io"

theme: just-the-docs

color_scheme: dark

mermaid:
  version: "10"

nav_sort: order
search_enabled: false
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "&copy; 2026 Vex Holdings. All rights reserved."

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
